shallow_clone: true
skip_tags: true
matrix:
  fast_finish: true
services:
  - mssql2014
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - echo %APPVEYOR_BUILD_FOLDER%
  - ruby --version
  - gem --version
  - bundle install
build: off
test_script:
  - powershell -NoExit -File "%APPVEYOR_BUILD_FOLDER%\test\appveyor\sqlserver_2014.ps1"
  - bundle exec rake TINYTDS_UNIT_DATASERVER="localhost\SQL2014" TINYTDS_UNIT_DATABASE=master TINYTDS_UNIT_USER=sa TINYTDS_UNIT_PASS=Password12!
environment:
  matrix:
    # - ruby_version: "193"
    #- ruby_version: "200"
    #- ruby_version: "200-x64"
    #- ruby_version: "21"
    #- ruby_version: "21-x64"
    #- ruby_version: "22"
    - ruby_version: "22-x64"
